### ISSUE TITLE
multizone thermostat turns off the heater, even if other zones actual temperature is still lower than its "target_temp_sensor"

### ISSUE THREAD

**Issue by atom83** [tpacri/multizone_generic_thermostat#16]
## Version of the custom_component
latest

## HA Version
2022.11.1

## Describe the bug
Hi,

Firs have to thank you, great addon you have created here, but somehow it is not working as expected.

You see in my config bellow I have 3 zones.
when I put all zones "target_temp_sensor" above their actual temperature, heating is on as expected, **but when I then set just one zones target_temp_sensor" below actual temperatur, the multizone thermostat turns off the heater, even if other zones actual temperature is still lower than its "target_temp_sensor".**  
Also perhaps worth to mention: After setting first zones target temp below the actual,  I see in the mz-thermostat card, that I gets a new target value, but still turns of the heater like stated.

I created a small video to visualize the behavior: https://i.imgur.com/1O8oGtr.mp4

Whats the problem here?

Thanks in advance.

Cheers
Thomas

## Configuration
```
input_number:
  min_wohnzimmer1_temperature:
    name: Min wz1  temperature
    initial: 18
    min: 14
    max: 25
    step: 0.1
  min_wohnzimmer2_temperature:
    name: Min wz2 temperature
    initial: 18
    min: 14
    max: 25
    step: 0.1
  min_schlafzimmer1_temperature:
    name: Min sz temperature
    initial: 18
    min: 14
    max: 25
    step: 0.1

climate:
  - platform: multizone_generic_thermostat
    unique_id: MainThermostat1
    name: MainThermostat
    heater: switch.relais1_1 
    presets:
        none:
            report_zone_name_instead_preset_name: true
            zones:
                living1:
                    target_sensors: 
                        - sensor.sensor_climate_2_temperature
                    target_temp_sensor: input_number.min_wohnzimmer1_temperature
                living2:
                    target_sensors: 
                        - sensor.sensor_climate_2_temperature
                    target_temp_sensor: input_number.min_wohnzimmer2_temperature
                sleeping:
                    target_sensors: 
                        - sensor.sensor_climate_1_temperature
                    target_temp_sensor: input_number.min_schlafzimmer1_temperature
    min_cycle_duration:
      seconds: 3
    initial_hvac_mode: "heat"
    ac_mode: false
    cold_tolerance: 0.2
    hot_tolerance: 0.2
```
